/* All editable content lives here. Change copy without touching layout or logic. */

// The 7 lenses — the spine of the whole guide. Color is "r,g,b".
const LENSES = [
  { n: 1, name: "User job",          color: "37,99,235",   ask: "What painful workflow are you solving?",
    detail: "Name a specific user, context, and struggle. Avoid “everyone.”" },
  { n: 2, name: "AI leverage",       color: "217,119,6",   ask: "Why is AI better than search, rules, templates, or manual work here?",
    detail: "AI shines at synthesis, generation, personalization, retrieval, and reasoning over messy context." },
  { n: 3, name: "Human-AI workflow", color: "124,58,237",  ask: "How does the user guide, review, edit, approve, or override the AI?",
    detail: "Think drafts, suggestions, copilots, review queues — not just a chatbot." },
  { n: 4, name: "Model behavior",    color: "13,148,136",  ask: "Where will the model be uncertain, wrong, slow, biased, or incomplete?",
    detail: "Hallucinations, stale data, brittleness on edge cases, latency and cost limits." },
  { n: 5, name: "Quality / evals",   color: "22,163,74",   ask: "What does “good” mean for this task, and how will you measure it?",
    detail: "Correctness, groundedness, acceptance rate, edit distance, escalation rate." },
  { n: 6, name: "Trust / failure",   color: "219,39,119",  ask: "How does the product fail safely?",
    detail: "Citations, previews before irreversible actions, approval checkpoints, graceful fallback." },
  { n: 7, name: "Learning loop",     color: "99,102,241",  ask: "How does the system improve from real usage?",
    detail: "Collect corrections, label bad outputs, turn recurring failures into eval cases." },
];

// §6 — phrases
const PHRASES = [
  "I'd first ask whether AI is the right solution, or whether a rules-based workflow is enough.",
  "I'd separate product success metrics from AI quality metrics.",
  "I'd launch this as a copilot before making it an autopilot.",
  "The model doesn't need to be perfect if the workflow is designed around review, correction, and safe failure.",
  "The product question isn't just whether the model can do it — it's whether users can trust, verify, and recover from what it does.",
];

// §8 — Answer Builder scenarios. Steps reference a lens number; name + color
// come from LENSES, so we never repeat them here.
const SCENARIOS = [
  {
    id: "support",
    label: "Support copilot",
    prompt: "Design an AI assistant for customer support agents handling refund tickets.",
    steps: [
      { lens: 1, q: "Who's the user, and what's the painful job?",
        answer: "I'll focus on support agents handling refund tickets — reading customer history, finding the right policy, and drafting a reply without making wrong promises.",
        choices: [
          { t: "Support agents handling refund tickets — reading history, finding policy, and drafting a reply without wrong promises.", strong: true,
            fb: "A specific user, context, and struggle. That's where every strong answer starts." },
          { t: "Everyone who contacts customer support.", strong: false,
            fb: "“Everyone” is a non-answer. Name a specific user and the painful job they're stuck on." },
          { t: "Customers, who just want instant refunds.", strong: false,
            fb: "Tempting, but the user of this tool is the agent. Pick the user who actually operates the product." },
        ]},
      { lens: 2, q: "Why is AI better here than a non-AI alternative?",
        answer: "AI earns its place by synthesizing messy ticket history and drafting a grounded first reply — something rules or search alone can't do well.",
        choices: [
          { t: "It synthesizes messy ticket history and drafts a grounded reply — work rules and search can't do well.", strong: true,
            fb: "You tied AI to a job it's uniquely good at: synthesis over messy context. That's leverage, not novelty." },
          { t: "It makes the product feel modern and AI-powered.", strong: false,
            fb: "That's novelty, not leverage. Name the specific capability AI adds that the alternatives can't." },
          { t: "Add a chatbot so customers can self-serve refunds.", strong: false,
            fb: "That swaps the user and reaches for “chatbot” by reflex. Stay on the agent's job." },
        ]},
      { lens: 3, q: "How does the agent actually work with the AI?",
        answer: "The AI drafts and cites the relevant policy; the agent reviews, edits, and approves before anything is sent — a copilot, not an autopilot.",
        choices: [
          { t: "AI drafts and cites policy; the agent reviews, edits, and approves before anything sends.", strong: true,
            fb: "Copilot, not autopilot. That's how you ship value before the model is perfect." },
          { t: "AI auto-sends replies to clear the queue faster.", strong: false,
            fb: "Full autonomy on day one, on customer-facing replies, is how trust breaks. Keep a human in the loop first." },
          { t: "An open chat box where the agent asks the AI questions.", strong: false,
            fb: "Open chat is a weak default. A guided draft → review → approve flow beats free-form chat here." },
        ]},
      { lens: 4, q: "Where will the model fail?",
        answer: "The highest-risk failure is a confident policy claim that isn't grounded in our docs — so I'd watch for hallucination, stale data, and brittle edge cases.",
        choices: [
          { t: "A confident policy claim that isn't grounded in our docs — plus stale data and edge-case tickets.", strong: true,
            fb: "You named the specific, highest-risk failure, not just “hallucination is a risk.”" },
          { t: "Modern models are reliable enough; failure isn't a real concern.", strong: false,
            fb: "Overconfidence is the trap. Interviewers want to hear exactly how and where it breaks." },
          { t: "It might be a little slow sometimes.", strong: false,
            fb: "Latency is real but minor here. The dangerous failure is a wrong, confident answer." },
        ]},
      { lens: 5, q: "What does “good” mean, and how do you measure it?",
        answer: "I'd separate product success — time saved and resolution rate — from AI quality: groundedness, agent acceptance rate, and edit distance from draft to sent reply.",
        choices: [
          { t: "Separate product metrics (time saved, resolution rate) from AI quality (groundedness, acceptance rate, edit distance).", strong: true,
            fb: "Splitting product success from AI quality is the move that sounds AI-native." },
          { t: "Track engagement and clicks on the AI panel.", strong: false,
            fb: "Engagement doesn't tell you if the output was good. AI products need quality measures too." },
          { t: "Just measure overall accuracy.", strong: false,
            fb: "“Accuracy” alone is vague. Which dimension — groundedness? acceptance? edit distance?" },
        ]},
      { lens: 6, q: "How does the product fail safely?",
        answer: "It fails safely through source citations, clear “this is a draft” UI, and routing high-risk cases — large refunds, account security, angry customers — to a human.",
        choices: [
          { t: "Citations, a clear “draft” UI, and routing high-risk cases (big refunds, angry customers) to a human.", strong: true,
            fb: "Concrete safeguards mapped to risk. That's failing safely without breaking trust." },
          { t: "Add a small disclaimer that the AI can make mistakes.", strong: false,
            fb: "A disclaimer offloads the risk to the user. Design the workflow to fail safely instead." },
          { t: "We'll improve the model later to reduce errors.", strong: false,
            fb: "That's a non-answer to safety. The question is what happens when it's wrong, today." },
        ]},
      { lens: 7, q: "How does the system improve from real usage?",
        answer: "We'd log accepted, edited, and rejected drafts, review recurring failure categories weekly, and convert them into eval cases that make next month better.",
        choices: [
          { t: "Log accepted/edited/rejected drafts, review failure categories weekly, and turn them into eval cases.", strong: true,
            fb: "A real feedback loop: usage → failure categories → evals. That's AI-native iteration." },
          { t: "We'll learn from users over time.", strong: false,
            fb: "Too vague. What data, collected how, reviewed by whom? Name the loop." },
          { t: "Retrain the whole model every month.", strong: false,
            fb: "Retraining is rarely the first lever. Prompts, retrieval, data, and UX usually move quality faster." },
        ]},
    ],
  },
  {
    id: "duolingo",
    label: "Duolingo tutor",
    prompt: "Where should Duolingo use AI — and where should it avoid AI?",
    steps: [
      { lens: 1, q: "What is the learner's real job?",
        answer: "The learner's real job isn't getting answers — it's building durable language ability through practice, feedback, and repetition.",
        choices: [
          { t: "Building durable language ability through practice, feedback, and repetition — not getting quick answers.", strong: true,
            fb: "You anchored on the real outcome — durable ability — not surface completion." },
          { t: "Finishing lessons and keeping their streak alive.", strong: false,
            fb: "That's a proxy metric, not the job. Completion can rise while learning falls." },
          { t: "Getting instant translations whenever they're stuck.", strong: false,
            fb: "That's the trap — answers on demand can weaken the very learning you want." },
        ]},
      { lens: 2, q: "Where does AI genuinely help learning?",
        answer: "AI helps most where it improves practice: adaptive conversation, personalized correction of repeated mistakes, and level-matched exercises — not by handing over answers.",
        choices: [
          { t: "Adaptive conversation practice, personalized correction of repeated mistakes, and level-matched exercises.", strong: true,
            fb: "Three concrete leverage points tied to learning, not novelty." },
          { t: "A chatbot that answers any grammar question instantly.", strong: false,
            fb: "Open Q&A risks outsourcing the thinking. Aim AI at practice, not answers." },
          { t: "AI that translates whole sentences for the learner.", strong: false,
            fb: "Doing the work for them removes the productive struggle that builds skill." },
        ]},
      { lens: 3, q: "How does the learner work with the AI?",
        answer: "I'd build an AI roleplay mode — the learner picks a real-life scenario, the AI plays the other person, and gives short, specific feedback after the attempt, not during every sentence.",
        choices: [
          { t: "AI roleplays a real-life scenario; the learner responds, and gets short feedback after the attempt.", strong: true,
            fb: "Feedback after the attempt protects the struggle while still coaching." },
          { t: "AI corrects every word the moment the learner types it.", strong: false,
            fb: "Constant interruption removes effort and recall. Let them attempt first." },
          { t: "AI gives the learner the perfect answer to copy.", strong: false,
            fb: "Copying isn't practicing. The learner has to produce the language themselves." },
        ]},
      { lens: 4, q: "Where will the model fail learners?",
        answer: "The risky failure is confident feedback when the model is actually unsure — including treating one acceptable phrasing as the only correct answer.",
        choices: [
          { t: "Confident corrections when it's unsure, and treating one valid phrasing as the only correct answer.", strong: true,
            fb: "You spotted the teaching-specific failure: false certainty harms learners." },
          { t: "It won't fail much — language is well within model ability.", strong: false,
            fb: "Overconfidence again. Language has many valid answers; the model can be wrongly rigid." },
          { t: "It might occasionally be slow to respond.", strong: false,
            fb: "Minor here. The real risk is wrong feedback delivered with confidence." },
        ]},
      { lens: 5, q: "What does “good” mean for an AI tutor?",
        answer: "I'd measure learning, not just engagement: improvement on repeated-mistake areas, week-later retention, learner confidence, and human-reviewed feedback quality.",
        choices: [
          { t: "Improvement on weak areas, week-later retention, confidence, and human-reviewed feedback quality.", strong: true,
            fb: "Learning outcomes over engagement — exactly the AI-quality split." },
          { t: "Daily active users and lesson completion rate.", strong: false,
            fb: "Engagement can rise while learning falls. Measure the learning, too." },
          { t: "How many messages the learner exchanges with the AI.", strong: false,
            fb: "Volume isn't value. More chatting doesn't mean more learning." },
        ]},
      { lens: 6, q: "How does it fail safely for a learner?",
        answer: "It fails safely by holding back high-confidence corrections when unsure, and making clear when it's offering one valid phrasing versus the only right answer.",
        choices: [
          { t: "Hold back confident corrections when unsure; distinguish “one valid way” from “the only correct answer.”", strong: true,
            fb: "Calibrated humility protects trust and avoids teaching wrong rules." },
          { t: "Always give a single confident correction so learners aren't confused.", strong: false,
            fb: "False confidence teaches wrong rules. Better to flag uncertainty." },
          { t: "Add a disclaimer that the AI may be wrong.", strong: false,
            fb: "A disclaimer doesn't fix bad feedback. Design the feedback to be honest about certainty." },
        ]},
      { lens: 7, q: "How does it improve over time?",
        answer: "It improves by turning each learner's repeated mistakes into future practice and human-reviewing feedback samples for teaching quality.",
        choices: [
          { t: "Turn repeated mistakes into future practice, and human-review feedback samples for teaching quality.", strong: true,
            fb: "The loop closes on learning outcomes, not just usage." },
          { t: "Show more lessons and ads to the most active users.", strong: false,
            fb: "That's monetization, not a learning loop. Improve the teaching." },
          { t: "Wait for app-store reviews to tell us what's wrong.", strong: false,
            fb: "Too slow and coarse. Use in-product signal: mistakes, corrections, feedback quality." },
        ]},
    ],
  },
];

// §7 — practice questions
const LEVELS = [
  { title: "Level 1 — AI feature sense", qs: [
    "How would you add an AI assistant to Google Calendar?",
    "Design an AI feature for Spotify that helps users discover music.",
    "How would you improve Duolingo using generative AI?",
    "Build an AI copilot for customer support agents.",
  ]},
  { title: "Level 2 — AI-native product judgment", qs: [
    "When should a product not use AI?",
    "How would you decide whether to use an LLM or a rules-based system?",
    "How would you launch an AI feature when the model is only right 80% of the time?",
    "How would you design trust into an AI writing assistant?",
  ]},
  { title: "Level 3 — evals, agents, and systems", qs: [
    "How would you evaluate an AI search product?",
    "Design an AI agent that books travel for busy professionals.",
    "What metrics would you track for an AI coding assistant?",
    "How would you reduce hallucinations in a legal research assistant?",
  ]},
];
